INSERT INTO cabinet VALUES
(501, 'Black', 'ATX', 'Metal') ,
(502, 'Black', 'ATX', 'Tempered Glass & Metal') ,
(503, 'Black', 'ATX', 'Stainless Steel') ,
(504, 'Black', 'ITX', 'Plastic') ,
(505, 'Black', 'ITX', 'Metal') ,
(506, 'Black', 'ITX', 'Tempered Glass & Metal') ,
(507, 'Black', 'ITX', 'Stainless Steel') ,
(508, 'Black', 'Mini ATX', 'Plastic') ,
(509, 'Black', 'Mini ATX', 'Metal') ,
(510, 'Black', 'Mini ATX', 'Tempered Glass & Metal') ,
(511, 'Black', 'Mini ATX', 'Stainless Steel') ,
(512, 'Black', 'Micro ATX', 'Plastic') ,
(513, 'Black', 'Micro ATX', 'Metal') ,
(514, 'Black', 'Micro ATX', 'Tempered Glass & Metal') ,
(515, 'Black', 'Micro ATX', 'Stainless Steel') ,
(516, 'Black', 'Micro ITX', 'Plastic') ,
(517, 'Black', 'Micro ITX', 'Metal') ,
(518, 'Black', 'Micro ITX', 'Tempered Glass & Metal') ,
(519, 'Black', 'Micro ITX', 'Stainless Steel') ,
(520, 'Grey', 'ATX', 'Plastic') ,
(521, 'Grey', 'ATX', 'Metal') ,
(522, 'Grey', 'ATX', 'Tempered Glass & Metal') ,
(523, 'Grey', 'ATX', 'Stainless Steel') ,
(524, 'Grey', 'ITX', 'Plastic') ,
(525, 'Grey', 'ITX', 'Metal') ,
(526, 'Grey', 'ITX', 'Tempered Glass & Metal') ,
(527, 'Grey', 'ITX', 'Stainless Steel') ,
(528, 'Grey', 'Mini ATX', 'Plastic') ,
(529, 'Grey', 'Mini ATX', 'Metal') ,
(530, 'Grey', 'Mini ATX', 'Tempered Glass & Metal') ,
(531, 'Grey', 'Mini ATX', 'Stainless Steel') ,
(532, 'Grey', 'Micro ATX', 'Plastic') ,
(533, 'Grey', 'Micro ATX', 'Metal') ,
(534, 'Grey', 'Micro ATX', 'Tempered Glass & Metal') ,
(535, 'Grey', 'Micro ATX', 'Stainless Steel') ,
(536, 'Grey', 'Micro ITX', 'Plastic') ,
(537, 'Grey', 'Micro ITX', 'Metal') ,
(538, 'Grey', 'Micro ITX', 'Tempered Glass & Metal') ,
(539, 'Grey', 'Micro ITX', 'Stainless Steel') ,
(540, 'White', 'ATX', 'Plastic') ,
(541, 'White', 'ATX', 'Metal') ,
(542, 'White', 'ATX', 'Tempered Glass & Metal') ,
(543, 'White', 'ATX', 'Stainless Steel') ,
(544, 'White', 'ITX', 'Plastic') ,
(545, 'White', 'ITX', 'Metal') ,
(546, 'White', 'ITX', 'Tempered Glass & Metal') ,
(547, 'White', 'ITX', 'Stainless Steel') ,
(548, 'White', 'Mini ATX', 'Plastic') ,
(549, 'White', 'Mini ATX', 'Metal') ,
(550, 'White', 'Mini ATX', 'Tempered Glass & Metal') ,
(551, 'White', 'Mini ATX', 'Stainless Steel') ,
(552, 'White', 'Micro ATX', 'Plastic') ,
(553, 'White', 'Micro ATX', 'Metal') ,
(554, 'White', 'Micro ATX', 'Tempered Glass & Metal') ,
(555, 'White', 'Micro ATX', 'Stainless Steel') ,
(556, 'White', 'Micro ITX', 'Plastic') ,
(557, 'White', 'Micro ITX', 'Metal') ,
(558, 'White', 'Micro ITX', 'Tempered Glass & Metal') ,
(559, 'White', 'Micro ITX', 'Stainless Steel') ,
(560, 'Blue', 'ATX', 'Plastic') ,
(561, 'Blue', 'ATX', 'Metal') ,
(562, 'Blue', 'ATX', 'Tempered Glass & Metal') ,
(563, 'Blue', 'ATX', 'Stainless Steel') ,
(564, 'Blue', 'ITX', 'Plastic') ,
(565, 'Blue', 'ITX', 'Metal') ,
(566, 'Blue', 'ITX', 'Tempered Glass & Metal') ,
(567, 'Blue', 'ITX', 'Stainless Steel') ,
(568, 'Blue', 'Mini ATX', 'Plastic') ,
(569, 'Blue', 'Mini ATX', 'Metal') ,
(570, 'Blue', 'Mini ATX', 'Tempered Glass & Metal') ,
(571, 'Blue', 'Mini ATX', 'Stainless Steel') ,
(572, 'Blue', 'Micro ATX', 'Plastic') ,
(573, 'Blue', 'Micro ATX', 'Metal') ,
(574, 'Blue', 'Micro ATX', 'Tempered Glass & Metal') ,
(575, 'Blue', 'Micro ATX', 'Stainless Steel') ,
(576, 'Blue', 'Micro ITX', 'Plastic') ,
(577, 'Blue', 'Micro ITX', 'Metal') ,
(578, 'Blue', 'Micro ITX', 'Tempered Glass & Metal') ,
(579, 'Blue', 'Micro ITX', 'Stainless Steel') ,
(580, 'Aqua', 'ATX', 'Plastic') ,
(581, 'Aqua', 'ATX', 'Metal') ,
(582, 'Aqua', 'ATX', 'Tempered Glass & Metal') ,
(583, 'Aqua', 'ATX', 'Stainless Steel') ,
(584, 'Aqua', 'ITX', 'Plastic') ,
(585, 'Aqua', 'ITX', 'Metal') ,
(586, 'Aqua', 'ITX', 'Tempered Glass & Metal') ,
(587, 'Aqua', 'ITX', 'Stainless Steel') ,
(588, 'Aqua', 'Mini ATX', 'Plastic') ,
(589, 'Aqua', 'Mini ATX', 'Metal') ,
(590, 'Aqua', 'Mini ATX', 'Tempered Glass & Metal') ,
(591, 'Aqua', 'Mini ATX', 'Stainless Steel') ,
(592, 'Aqua', 'Micro ATX', 'Plastic') ,
(593, 'Aqua', 'Micro ATX', 'Metal') ,
(594, 'Aqua', 'Micro ATX', 'Tempered Glass & Metal') ,
(595, 'Aqua', 'Micro ATX', 'Stainless Steel') ,
(596, 'Aqua', 'Micro ITX', 'Plastic') ,
(597, 'Aqua', 'Micro ITX', 'Metal') ,
(598, 'Aqua', 'Micro ITX', 'Tempered Glass & Metal') ,
(599, 'Aqua', 'Micro ITX', 'Stainless Steel') ,
(600, 'Cyan', 'ATX', 'Plastic') ;
