source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/schema.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/manager.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/customer.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/product.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/motherboard.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/gpu.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/processor.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/storage.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/ram.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/psu.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/cabinet.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/cart.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/invoice.sql
source C:/Users/gupta/Desktop/Folders/College/IIITD/Semesters/Semester 4/DBMS/NerdLab/DataBases/review.sql
