source /home/void/work/dbms/NerdLabs/database/schema.sql
source /home/void/work/dbms/NerdLabs/database/manager.sql
source /home/void/work/dbms/NerdLabs/database/customer.sql
source /home/void/work/dbms/NerdLabs/database/product.sql
source /home/void/work/dbms/NerdLabs/database/motherboard.sql
source /home/void/work/dbms/NerdLabs/database/gpu.sql
source /home/void/work/dbms/NerdLabs/database/processor.sql
source /home/void/work/dbms/NerdLabs/database/storage.sql
source /home/void/work/dbms/NerdLabs/database/ram.sql
source /home/void/work/dbms/NerdLabs/database/psu.sql
source /home/void/work/dbms/NerdLabs/database/cabinet.sql
source /home/void/work/dbms/NerdLabs/database/cart.sql
source /home/void/work/dbms/NerdLabs/database/invoice.sql
source /home/void/work/dbms/NerdLabs/database/review.sql
